version: 1
disable_existing_loggers: false

formatters:
  console_formatter:
    "()": "uvicorn.logging.DefaultFormatter"
    "fmt": "%(levelprefix)s [%(name)s] :: %(message)s"
    "use_colors": true

  file_formatter:
    "()": "uvicorn.logging.DefaultFormatter"
    "fmt": "%(asctime)s :: %(levelname)s :: [%(name)s] :: %(message)s"
    "use_colors": false

handlers:
  console:
    "class": "logging.StreamHandler"
    "formatter": "console_formatter"
    "stream": "ext://sys.stdout"

  file:
    "class": "logging.FileHandler"
    "formatter": "file_formatter"
    "filename": "bms_bridge.log"
    "mode": "w"
    "encoding": "utf-8"

root:
  level: INFO
  handlers: [console, file]